export const DEFAULT_CONFIG = {
	assets: {
		include: ['./'],
		exclude: [
			'.DS_Store',
			'node_modules',
			'.git',
			'.gitignore',
			'.gitattributes',
			'.github',
			'.vscode',
			'LICENSE',
			'README.md',
			'CHANGELOG.md',
			'package.json',
			'package-lock.json',
			'yarn.lock',
			'pnpm-lock.yaml',
			'tsconfig.json',
			'tsconfig.build.json',
			'tsconfig.prod.json',
			'tsconfig.dev.json',
			'tsconfig.test.json',
			'jest.config.js',
			'jest.setup.js',
			'jest.setup.ts',
			'jest.setup.tsx',
			'jest.setup.js',
			'jest.setup.jsx',
			'jest.config.ts',
			'jest.config.tsx',
			'jest.config.js',
			'jest.config.jsx',
			'jest.config.json',
		],
	},
	files: {
		include: ['./'],
		exclude: ['node_modules', '.git', '.DS_Store'],
	},
};
